name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd minimal-react
        npm install
        npm run build

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: build for deployment
      uses: actions/checkout@v1
      with:
        node-version: 12.x
    - run: |
        cd minimal-react
        npm install
        npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
    - run: |
        cd minimal-react/build
        aws s3 cp --recursive --acl public-read --region ca-central-1 . s3://react-aws-github-integration-test
