name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd minimal-react
        npm install
        npm run build

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: actions/checkout@v1
      with:
        node-version: 12.x
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: |
        cd minimal-react
        npm install
        npm run build
        cd build
        aws s3 cp --recursive --acl public-read --region ca-central-1 . s3://react-aws-github-integration-test
